name: Run maven on demand
on:
  workflow_dispatch:
    inputs:
      maven_tasks:
        description: 'One, or many maven tasks to run (for multiple seperate with a space character [` `])'
        required: true
        default: '-B package --file pom.xml'
jobs:
  maven:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw ${{ github.event.inputs.maven_tasks }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swagger-codegen-cli.jar
          path: |
            modules/swagger-codegen-cli/target/swagger-codegen-cli.jar
