name: Run Swagger codegen verification on demand
on:
  workflow_dispatch:
    inputs:
      gradle_tasks:
        description: 'One, or many gradle tasks to run (for multiple seperate with a space character [` `])'
        required: true
        default: ':charthop-api:verifyGeneratedCodeIsFreeOfDiffs'
jobs:
  gradle:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw -B package --file pom.xml
